# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jobs:
    job1:
      runs-on: ubuntu-latest
      name: job1
      steps:
        - name: start minikube
          id: minikube
          uses: medyagh/setup-minikube@master
        # now you can run kubectl to see the pods in the cluster
        - name: kubectl
          run: kubectl get pods -A
