# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        # now you can run kubectl to see the pods in the cluster
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          minikube ip
          minikube version
          kubectl version
          env | sort
      #    make build-image
      #    echo -n "verifying images:"
      #    docker images
      #- name: Deploy to minikube
      #  run:
      #    kubectl apply -f deploy/deploy-minikube.yaml
      #- name: Test service URLs
      ##  run: |
      #    minikube service list
      #    minikube service discover --url
      #    echo -n "------------------opening the service------------------"
      #    curl $(minikube service discover --url)/version
