# This is a basic workflow to help you get started with Action
name: CI
on: [push, pull_request, workflow_dispatch]

# Controls when the action will run. 
#on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  end-to-end:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14.4'

      - uses: jpkrohling/setup-operator-sdk@v1.0.2
        with:
          operator-sdk-version: v0.18.2

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.1.0
        with:
          minikube version: 'v1.15.1'
          kubernetes version: 'v1.19.2'
          driver: docker
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start minikube script
        run: ./.ci/start-minikube.sh

      - name: Interact with the cluster
        run: kubectl get nodes

      - name: Build image 
        run: ./.ci/builddockerimage.sh

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kevinearls/httpexample
          tag_with_ref: true

      - name: Try using image
        run: ./.ci/trythis.sh
